root: true
env:
  serviceworker: true
  browser: true
  es2020: true
  node: true
  jest: true
parserOptions:
  ecmaVersion: 11
  sourceType: "module"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:react-hooks/recommended"
  - "airbnb"
  - "airbnb/hooks"
  - "prettier"
  - "prettier/react"
ignorePatterns:
  - "/*"
  - "!src/"
  - "index.js"
  - "css-reset"
  - "setupTests.js"
rules:
  camelcase: 0
  comma-dangle: 0
  linebreak-style:
    - "error"
    - "unix"
  no-plusplus: 0
  no-return-assign: 0
  no-param-reassign: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
  react/jsx-filename-extension: 0
  import/no-useless-path-segments: 0
